# Generated by Django 2.0.7 on 2018-07-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, verbose_name='path')),
                ('company', models.CharField(max_length=256, verbose_name='company')),
                ('product', models.CharField(max_length=256, verbose_name='product')),
                ('description', models.TextField(verbose_name='description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('author', models.CharField(max_length=256, verbose_name='author')),
            ],
        ),
    ]
