# Generated by Django 2.0.7 on 2018-07-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
